/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNDERSCORE = 1;
  /** RegularExpression Id. */
  int LEFT_PAREN = 2;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int PERIOD = 6;
  /** RegularExpression Id. */
  int STAR = 7;
  /** RegularExpression Id. */
  int QUOTE = 8;
  /** RegularExpression Id. */
  int SIGN = 9;
  /** RegularExpression Id. */
  int COMP_OP = 10;
  /** RegularExpression Id. */
  int SPACE = 11;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTER = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int ALPHABET = 14;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 15;
  /** RegularExpression Id. */
  int CHAR_STRING = 16;
  /** RegularExpression Id. */
  int INT_VALUE = 17;
  /** RegularExpression Id. */
  int DATE_VALUE = 18;
  /** RegularExpression Id. */
  int NNNN = 19;
  /** RegularExpression Id. */
  int NN = 20;
  /** RegularExpression Id. */
  int SELECT = 21;
  /** RegularExpression Id. */
  int FROM = 22;
  /** RegularExpression Id. */
  int WHERE = 23;
  /** RegularExpression Id. */
  int CREATE = 24;
  /** RegularExpression Id. */
  int TABLE = 25;
  /** RegularExpression Id. */
  int IS = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int INSERT = 30;
  /** RegularExpression Id. */
  int INTO = 31;
  /** RegularExpression Id. */
  int DELETE = 32;
  /** RegularExpression Id. */
  int NULL = 33;
  /** RegularExpression Id. */
  int DESC = 34;
  /** RegularExpression Id. */
  int DROP = 35;
  /** RegularExpression Id. */
  int SHOW = 36;
  /** RegularExpression Id. */
  int TABLES = 37;
  /** RegularExpression Id. */
  int VALUES = 38;
  /** RegularExpression Id. */
  int AS = 39;
  /** RegularExpression Id. */
  int PRIMARY = 40;
  /** RegularExpression Id. */
  int FOREIGN = 41;
  /** RegularExpression Id. */
  int KEY = 42;
  /** RegularExpression Id. */
  int INT = 43;
  /** RegularExpression Id. */
  int CHAR = 44;
  /** RegularExpression Id. */
  int DATE = 45;
  /** RegularExpression Id. */
  int REFERENCES = 46;
  /** RegularExpression Id. */
  int EXIT = 47;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"*\"",
    "\"\\\'\"",
    "<SIGN>",
    "<COMP_OP>",
    "<SPACE>",
    "<NON_QUOTE_SPECIAL_CHARACTER>",
    "<DIGIT>",
    "<ALPHABET>",
    "<NON_QUOTE_CHARACTER>",
    "<CHAR_STRING>",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"create\"",
    "\"table\"",
    "\"is\"",
    "<NOT>",
    "<AND>",
    "<OR>",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"null\"",
    "\"desc\"",
    "\"drop\"",
    "\"show\"",
    "\"tables\"",
    "<VALUES>",
    "\"as\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "<REFERENCES>",
    "\"exit\"",
    "<LEGAL_IDENTIFIER>",
  };

}
