/* Generated By:JavaCC: Do not edit this line. SQLParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UNDERSCORE = 1;
  /** RegularExpression Id. */
  int LEFT_PAREN = 2;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int PERIOD = 6;
  /** RegularExpression Id. */
  int STAR = 7;
  /** RegularExpression Id. */
  int QUOTE = 8;
  /** RegularExpression Id. */
  int SIGN = 9;
  /** RegularExpression Id. */
  int COMP_OP = 10;
  /** RegularExpression Id. */
  int SPACE = 11;
  /** RegularExpression Id. */
  int PURE_SPACE = 12;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTER = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int ALPHABET = 15;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 16;
  /** RegularExpression Id. */
  int CHAR_STRING = 17;
  /** RegularExpression Id. */
  int INT_VALUE = 18;
  /** RegularExpression Id. */
  int DATE_VALUE = 19;
  /** RegularExpression Id. */
  int NNNN = 20;
  /** RegularExpression Id. */
  int NN = 21;
  /** RegularExpression Id. */
  int SELECT = 22;
  /** RegularExpression Id. */
  int FROM = 23;
  /** RegularExpression Id. */
  int WHERE = 24;
  /** RegularExpression Id. */
  int CREATE = 25;
  /** RegularExpression Id. */
  int TABLE = 26;
  /** RegularExpression Id. */
  int IS = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int INSERT = 31;
  /** RegularExpression Id. */
  int INTO = 32;
  /** RegularExpression Id. */
  int DELETE = 33;
  /** RegularExpression Id. */
  int NULL = 34;
  /** RegularExpression Id. */
  int DESC = 35;
  /** RegularExpression Id. */
  int DROP = 36;
  /** RegularExpression Id. */
  int SHOW = 37;
  /** RegularExpression Id. */
  int TABLES = 38;
  /** RegularExpression Id. */
  int VALUES = 39;
  /** RegularExpression Id. */
  int AS = 40;
  /** RegularExpression Id. */
  int PRIMARY = 41;
  /** RegularExpression Id. */
  int FOREIGN = 42;
  /** RegularExpression Id. */
  int KEY = 43;
  /** RegularExpression Id. */
  int INT = 44;
  /** RegularExpression Id. */
  int CHAR = 45;
  /** RegularExpression Id. */
  int DATE = 46;
  /** RegularExpression Id. */
  int REFERENCES = 47;
  /** RegularExpression Id. */
  int EXIT = 48;
  /** RegularExpression Id. */
  int EXCEPT_SEMICOLON = 49;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"*\"",
    "\"\\\'\"",
    "<SIGN>",
    "<COMP_OP>",
    "<SPACE>",
    "\" \"",
    "<NON_QUOTE_SPECIAL_CHARACTER>",
    "<DIGIT>",
    "<ALPHABET>",
    "<NON_QUOTE_CHARACTER>",
    "<CHAR_STRING>",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"create\"",
    "\"table\"",
    "\"is\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"null\"",
    "\"desc\"",
    "\"drop\"",
    "\"show\"",
    "\"tables\"",
    "\"values\"",
    "\"as\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"references\"",
    "\"exit\"",
    "<EXCEPT_SEMICOLON>",
    "<LEGAL_IDENTIFIER>",
  };

}
